trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/*
    exclude:
    - instructions/*
    - presentation/*
    - workspace/*

pool:
  vmImage: 'windows-latest'

variables:
- group: fraud-detection
- name: buildConfiguration
  value: 'Release'

steps:
- script: 'net use X: \\filesharepublic.file.core.windows.net\data /u:filesharepublic $(filestorage.key)'
  displayName: 'Map disk drive to Azure Files share folder'
  
- script: dotnet build src/machine-learning/FraudPredictionTrainer/FraudPredictionTrainer.csproj --configuration $(buildConfiguration)
  displayName: 'Build Trainer Console App (dotnet build) $(buildConfiguration)'

- script: dotnet run --project src/machine-learning/FraudPredictionTrainer/FraudPredictionTrainer.csproj --configuration $(buildConfiguration)
  displayName: 'Train ML model (dotnet run)'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests using trained ML model'
  inputs:
    command: test
    projects: 'src/machine-learning/FraudPrediction.Tests/FraudPrediction.Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'